version: "3.1"

services:
  loggyfier.local:
    build: docker/apache
    volumes:
      - .:/app:cached
    ports:
      - "8080:80"
    environment:
      - VIRTUAL_HOST=loggyfier.local

  redis.loggyfier.local:
    build: docker/redis
    ports:
      - "6379:6379"
    volumes:
      - ./persistence/redis:/data
